version: '3.9'
services:
  app:
    build: .
    image: powercross-app:dev
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - NOTIFY_EMAIL=${NOTIFY_EMAIL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PRICE_ID=${STRIPE_PRICE_ID}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - PLAUSIBLE_DOMAIN=${PLAUSIBLE_DOMAIN}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - prisma-db:/app/prisma
    command: sh -lc "npm run dev"
volumes:
  prisma-db:
